[package]
name = "taurpc"
authors = ["MatsDK"]
version = "0.1.2"
edition = "2021"
description = "A type-safe RPC layer for tauri commands"
documentation = "https://docs.rs/taurpc"
homepage = "https://github.com/MatsDK/TauRPC"
repository = "https://github.com/MatsDK/TauRPC"
license = "MIT OR Apache-2.0"
readme = "../README.md"
categories = ["tauri"]

[workspace]
members = [
  "taurpc-macros",
]

[dependencies]
taurpc-macros = { path = "./taurpc-macros", version = "0.1.1" }

ts-rs = "6.2"
tauri = { version = "1.3" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.96"