[package]
name = "taurpc"
authors = ["MatsDK"]
version = "0.3.1"
edition = "2021"
description = "A type-safe IPC layer for tauri commands"
documentation = "https://docs.rs/taurpc"
homepage = "https://github.com/MatsDK/TauRPC"
repository = "https://github.com/MatsDK/TauRPC"
license = "MIT OR Apache-2.0"
readme = "../README.md"
categories = []
rust = "1.71"

[workspace]
members = [
  "taurpc-macros",
]

[dependencies]
itertools = "0.13.0"
taurpc-macros = { path = "./taurpc-macros", version = "=0.3.1" }
specta = { version = "=2.0.0-rc.20" }
tauri = "2.1.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1", features = ["full"] }
specta-serde = { version = "0.0.7", features = [] }
specta-typescript = { version = "0.0.7", features = ["function"] }
specta-util = { version = "0.0.7", features = ["export"] }
specta-macros = { version = "2.0.0-rc.17" }
