[package]
name = "taurpc"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "taurpc-macros",
]

[dependencies]
taurpc-macros = { path = "./taurpc-macros" }

ts-rs = "6.2"
tauri = { version = "1.3" }
serde = { version = "1", features = ["derive"] }
